---
author: "Jun Cheng"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 4
vignette: >
  %\VignetteIndexEntry{ggpval user guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

`ggpval` allow you to generate statistical test and add test p-value to plots automatically. P-valules can be presented as formated p-values or with stars (e.g. *, **). Alternatively one can also annotation groups with text.


## Example

Simulate data with groups.

```{r, fig.show='hold'}
library(ggpval)
library(data.table)
library(ggplot2)
A <- rnorm(200, 0, 3)
B <- rnorm(200, 2, 4)
G <- rep(c("G1", "G2"), each = 100)
dt <- data.table(A, B, G)
dt <- melt(dt, id.vars = "G")
```


## A trivial boxplot example

Give group pairs you want to compare in `pairs`.

```{r, echo=FALSE, results='asis'}
plt <- ggplot(dt, aes(variable, value)) +
  geom_boxplot() +
  geom_jitter()

add_pval(plt, pairs = list(c(1, 2)))
```

## Boxplot with facets

```{r, echo=FALSE, results='asis'}
plt_facet <- ggplot(dt, aes(variable, value)) +
  geom_boxplot() +
  geom_jitter() +
  facet_wrap(~G)
add_pval(plt_facet, pairs = list(c(1, 2)))
```

## Annotate your plot
```{r, echo=FALSE, results='asis'}
add_pval(plt_facet, pairs = list(c(1, 2)), annotation = "Awesome")
```
